name: norm_rl
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - alembic=1.18.0
  - alsa-lib=1.2.15.3
  - aom=3.9.1
  - attr=2.5.2
  - bottle=0.13.4
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - colorlog=6.10.1
  - cpython=3.13.11
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.19
  - farama-notifications=0.0.4
  - ffmpeg=8.0.1
  - filelock=3.20.3
  - fmt=12.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2026.1.0
  - gdk-pixbuf=2.44.4
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.3.0
  - gymnasium=1.0.0
  - harfbuzz=12.3.0
  - icu=78.2
  - importlib-metadata=8.7.0
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - jax-jumpy=1.0.0
  - jinja2=3.1.6
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.27.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libblas=3.11.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcudss=0.7.1.4
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libmpdec=4.0.0
  - libnl=3.11.0
  - libntlm=1.8
  - libnvjitlink=12.9.86
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopengl-devel=1.7.0
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=18.1
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - mako=1.3.10
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - nccl=2.29.2.1
  - ncurses=6.5
  - networkx=3.6.1
  - numpy=2.4.1
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openldap=2.6.10
  - openssl=3.6.0
  - optree=0.18.0
  - optuna=4.6.0
  - optuna-dashboard=0.20.0
  - packaging=25.0
  - pango=1.56.4
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - psycopg2=2.9.11
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pyglet=2.0.20
  - pyopengl=3.1.10
  - python=3.13.11
  - python-dotenv=1.2.1
  - python_abi=3.13
  - pytorch=2.9.1
  - pyyaml=6.0.3
  - rdma-core=60.0
  - readline=8.3
  - sdl2=2.32.56
  - sdl3=3.2.30
  - setuptools=80.9.0
  - shaderc=2025.5
  - sleef=3.9.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - sqlalchemy=2.0.45
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - tomli=2.4.0
  - tqdm=4.67.1
  - triton=3.5.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wayland=1.24.0
  - wayland-protocols=1.47
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - yaml=0.2.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
    - DataProperty==1.1.0
    - ImageIO==2.37.2
    - Markdown==3.10
    - Pygments==2.19.2
    - Shimmy==2.0.0
    - Werkzeug==3.1.5
    - absl-py==2.3.1
    - aiofiles==25.1.0
    - ale-py==0.11.2
    - certifi==2026.1.4
    - chardet==5.2.0
    - charset-normalizer==3.4.4
    - chex==0.1.91
    - contourpy==1.3.3
    - cycler==0.12.1
    - decorator==5.2.1
    - etils==1.13.0
    - flax==0.12.2
    - fonttools==4.61.1
    - grpcio==1.76.0
    - hf-xet==1.2.0
    - huggingface-hub==0.36.0
    - huggingface-sb3==3.0
    - humanize==4.15.0
    - idna==3.11
    - imageio-ffmpeg==0.6.0
    - importlib_resources==6.5.2
    - jax==0.8.2
    - jaxlib==0.8.2
    - kiwisolver==1.4.9
    - markdown-it-py==4.0.0
    - matplotlib==3.10.8
    - mbstrdecoder==1.1.4
    - mdurl==0.1.2
    - ml_dtypes==0.5.4
    - moviepy==2.2.1
    - msgpack==1.1.2
    - nest-asyncio==1.6.0
    - numpy==2.2.6
    - opencv-python==4.12.0.88
    - opt_einsum==3.4.0
    - optax==0.2.6
    - orbax-checkpoint==0.11.31
    - pandas==2.3.3
    - pathvalidate==3.3.1
    - pillow==11.3.0
    - proglog==0.1.12
    - protobuf==6.33.4
    - psutil==7.2.1
    - pyflame==0.3.2
    - pygame==2.6.1
    - pyparsing==3.3.1
    - pytablewriter==1.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.5
    - rich==14.2.0
    - rl_zoo3==2.6.0
    - sb3_contrib==2.6.0
    - scipy==1.17.0
    - simplejson==3.20.2
    - six==1.17.0
    - stable_baselines3==2.6.0
    - tabledata==1.3.4
    - tcolorpy==0.1.7
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorstore==0.1.80
    - toolz==1.1.0
    - treescope==0.1.10
    - typepy==1.3.4
    - tzdata==2025.3
    - urllib3==2.6.3
    - wasabi==1.1.3

